services:
  webserver:
    image: nginx:latest
    ports:
      - "3001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app
  php:
    image: php:fpm
    volumes:
      - ./src:/app