service: service-cake-ordering
plugins:
  # Use CloudFormation Pseudo Parameters in your Serverless project
  - serverless-pseudo-parameters
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-1
  timeout: ${self:provider.environment.LAMBDA_TIMEOUT}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.ORDER_TABLE}
    - Effect: Allow
      Action:
        - kinesis:PutRecord
      Resource:
        - arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/${self:provider.environment.ORDER_STREAM}
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource:
        - "*"
      Condition:
        StringEquals:
          ses:FromAddress:
            - ${self:provider.environment.CAKE_ORDER_EMAIL}
  environment:
    ORDER_TABLE: cake-orders
    ORDER_STREAM: order-events
    LAMBDA_TIMEOUT: 900
    SES_REGION: us-east-1
    CAKE_PRODUCER_EMAIL: endlesslovefor123@gmail.com
    CAKE_ORDER_EMAIL: nguyenlc@runsystem.net
    DELIVERY_COMPANY_EMAIL: xspacechinguyen@gmail.com
functions:
  - ${file(./config-modules/functions.yml)}
resources:
  - ${file(./config-modules/resources.yml)}
