# settings.yaml
box_name: "bento/ubuntu-22.04"
vm:
- name: "controlplane"
  ip: "192.168.201.10"
  memory: "2048"
  cpus: "2"
- name: "node01"
  ip: "192.168.201.11"
  memory: "2048"
  cpus: "1"
- name: "node02"
  ip: "192.168.201.12"
  memory: "2048"
  cpus: "1"
